[package]
name = "AudioMerge"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.55", features = ["derive"] }
natord = "1.0.9"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.24.0"
