[package]
name = "spell-i-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
swift-bridge = "0.1"
harper-core = "1"

[build-dependencies]
swift-bridge-build = "0.1"
