[package]
name = "stash-mgr"
version = "0.1.0"
edition = "2024"
authors = ["Winter Faulk"]

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
git2 = "0.20"
color-eyre = "0.6"
strum = { version = "0.26", features = ["derive"] }
